name: build and deploy Sentinel

pool:  
  name: Azure Pipelines
  vmImage: 'windows-latest'

trigger: none 

stages:
  - stage: Customer
    displayName: 'Deploying to Customer environment'
    jobs:
      - template: ../Pipelines/OnboardCustomer.yml
        parameters:
            CustomerName: 'Customer2'
            HostingNumber: '234567'
            WorkspaceName: 'H234567-dev'
            ResourceGroupName: 'H234567-rg'
            ResourceGroupLocation: 'eastus'
            ServiceConnectionName: 'ARM Sub 2'
