name: Build and deploy Sentinel for new customers
resources:
 pipelines:
   - pipeline: Scripts
     source: 'scriptsCI'
trigger:
 paths:
   include:
     - Onboard/*.json
   exclude:
     - Onboard/Completed/*
stages:
- stage: One
  displayName: 'Getting new customer onboarding file'
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
  jobs:
    - job: A
      displayName: 'Copy, validate, publish'
      steps:
       - task: CopyFiles@2
         displayName: 'Copy new customer onboarding json'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          TargetFolder: '$(Pipeline.Workspace)/s/Deploy'
       - task: Files-Validator@1
         displayName: 'Validating JSON'
         inputs:
          rootDir: '$(Pipeline.Workspace)/s/Deploy/*.json'
          validateXML: false
          validateJSON: true
          validateYAML: false
          validatePS: false
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: OnboardingFile'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)/s/Deploy'
          Contents: '*.json'
          ArtifactName: OnboardingFile
       - pwsh: |
            $variables = Get-Content $(Pipeline.Workspace)/s/Deploy/*.json | ConvertFrom-Json -AsHashtable
            $variables.GetEnumerator() | ForEach-Object {
              $name = $_.key
              $value = $_.value
              Write-Host "##vso[task.setvariable variable=$name]$value"
            }
         name: SetVars
         displayName: 'Parse JSON into variables'
       - task: Bash@3
         name: GetVars
         displayName: 'Print variables'
         inputs:
          targetType: inline
          script: |
            echo "CustomerName = $(CustomerName)"
            echo "HostingNumber = $(HostingNumber)"
            echo "WorkspaceName = $(WorkspaceName)"
            echo "ResourceGroupName = $(ResourceGroupName)"
            echo "ResourceGroupLocation = $(ResourceGroupLocation)"
            echo "ServiceConnectionName = $(ServiceConnectionName)"

- stage: Two
  displayName: 'Deploying to Customer environment'
  dependsOn:
    - One
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
  jobs:
    - job: B
      displayName: 'Print variables'
      variables:
        CustomerName: $[ stageDependencies.One.A.outputs['GetVars.CustomerName'] ]
        HostingNumber: $[ stageDependencies.one.A.outputs['GetVars.HostingNumber'] ]
        WorkspaceName: $[ stageDependencies.one.A.outputs['GetVars.WorkspaceName'] ]
        ResourceGroupName: $[ stageDependencies.one.A.outputs['GetVars.ResourceGroupName'] ]
        ResourceGroupLocation: $[ stageDependencies.one.A.outputs['GetVars.ResourceGroupLocation'] ]
        ServiceConnectionName: $[ stageDependencies.one.A.outputs['GetVars.ServiceConnectionName'] ]
      steps:
      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            echo "CustomerName = $(CustomerName)"
            echo "HostingNumber = $(HostingNumber)"
            echo "WorkspaceName = $(WorkspaceName)"
            echo "ResourceGroupName = $(ResourceGroupName)"
            echo "ResourceGroupLocation = $(ResourceGroupLocation)"
            echo "ServiceConnectionName = $(ServiceConnectionName)"

- stage: Three
  displayName: 'Clean up onboarding files'
  dependsOn: 
    - One
    - Two
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
  jobs:
    - job: C
      displayName: 'Cleanup'
      steps:
       - checkout: self
         persistCredentials: true
         fetchDepth: 0
       - task: CopyFiles@2
         displayName: 'Copy new customer onboarding json to completed'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          TargetFolder: '$(Pipeline.Workspace)/s/Onboard/Completed'
       - task: Files-Validator@1
         displayName: 'Validating JSON'
         inputs:
           rootDir: '$(Pipeline.Workspace)/s/Onboard'
           validateXML: false
           validateJSON: true
           validateYAML: false
           validatePS: false
       - task: DeleteFiles@1
         displayName: 'Remove unneeded files'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
       - script: |
          git config --global user.email "marcackermann860@gmail.com"
          git config --global user.name "marcackermann86"
          git checkout master
          git add --all
          git commit -m "Moving deployed customers"
          git push origin master
         workingDirectory: '$(Pipeline.Workspace)/s/Onboard/Completed'