name: Build and deploy Sentinel for new customers

resources:
 pipelines:
   - pipeline: Scripts
     source: 'scriptsCI'
     
trigger:
 paths:
   include:
     - Onboard/*.json
   exclude:
     - Onboard/Completed/*

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

stages:
- stage: A
  displayName: 'Getting new customer onboarding file'
  jobs:
    - job: A1
      displayName: 'Copy, validate, publish'
      steps:
       - task: CopyFiles@2
         displayName: 'Copy new customer onboarding json'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          TargetFolder: '$(Pipeline.Workspace)/s/Deploy'
       - task: Files-Validator@1
         displayName: 'Validating JSON'
         inputs:
          rootDir: '$(Pipeline.Workspace)/s/Deploy/*.json'
          validateXML: false
          validateJSON: true
          validateYAML: false
          validatePS: false
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: OnboardingFile'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)/s/Deploy'
          Contents: '*.json'
          ArtifactName: OnboardingFile
       - pwsh: |
            $variables = Get-Content $(Pipeline.Workspace)/s/Deploy/*.json | ConvertFrom-Json -AsHashtable
            $variables.GetEnumerator() | ForEach-Object {
              $name = $_.key
              $value = $_.value
              Write-Host "##vso[task.setvariable variable=$name]$value"
            }
         name: SetVars
         displayName: 'Parse JSON into variables'
       - task: Bash@3
         displayName: 'Print variables'
         inputs:
          targetType: inline
          script: |
            echo "CustomerName = $(CustomerName)"
            echo "HostingNumber = $(HostingNumber)"
            echo "WorkspaceName = $(WorkspaceName)"
            echo "ResourceGroupName = $(ResourceGroupName)"
            echo "ResourceGroupLocation = $(ResourceGroupLocation)"
            echo "ServiceConnectionName = $(ServiceConnectionName)"

- stage: B
  displayName: 'Deploying to Customer environment'
  dependsOn:
    - A
  jobs:
    - job: B1
      displayName: 'Print variables'
      variables:
        CustomerName0: $[ stageDependencies.A.A1.SetVars.outputs['CustomerName'] ]
        CustomerName1: $[ stageDependencies.A.A1.SetVars.outputs['SetVars.CustomerName'] ]
        CustomerName2: $[ stageDependencies.A.A1.SetVars.outputs['A1.SetVars.CustomerName'] ]
        CustomerName3: $[ stageDependencies.A.A1.outputs['CustomerName'] ]
        CustomerName4: $[ stageDependencies.A.A1.outputs['SetVars.CustomerName'] ]
        CustomerName5: $[ stageDependencies.A.A1.outputs['A1.SetVars.CustomerName'] ]
        CustomerName6: $[ stageDependencies.A.outputs['CustomerName'] ]
        CustomerName7: $[ stageDependencies.A.outputs['SetVars.CustomerName'] ]
        CustomerName8: $[ stageDependencies.A.outputs['A1.SetVars.CustomerName'] ]

        CustomerName10: $[ dependencies.A.A1.SetVars.outputs['CustomerName'] ]
        CustomerName11: $[ dependencies.A.A1.SetVars.outputs['SetVars.CustomerName'] ]
        CustomerName12: $[ dependencies.A.A1.SetVars.outputs['A1.SetVars.CustomerName'] ]
        CustomerName13: $[ dependencies.A.A1.outputs['CustomerName'] ]
        CustomerName14: $[ dependencies.A.A1.outputs['SetVars.CustomerName'] ]
        CustomerName15: $[ dependencies.A.A1.outputs['A1.SetVars.CustomerName'] ]
        CustomerName16: $[ dependencies.A.outputs['CustomerName'] ]
        CustomerName17: $[ dependencies.A.outputs['SetVars.CustomerName'] ]
        CustomerName18: $[ dependencies.A.outputs['A1.SetVars.CustomerName'] ]
      steps:
      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            echo "CustomerName = $(CustomerName)"
            echo "HostingNumber = $(HostingNumber)"
            echo "WorkspaceName = $(WorkspaceName)"
            echo "ResourceGroupName = $(ResourceGroupName)"
            echo "ResourceGroupLocation = $(ResourceGroupLocation)"
            echo "ServiceConnectionName = $(ServiceConnectionName)"

- stage: C
  displayName: 'Clean up onboarding files'
  dependsOn: 
    - A
    - B
  jobs:
    - job: C1
      displayName: 'Cleanup'
      steps:
       - checkout: self
         persistCredentials: true
         fetchDepth: 0
       - task: CopyFiles@2
         displayName: 'Copy new customer onboarding json to completed'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          TargetFolder: '$(Pipeline.Workspace)/s/Onboard/Completed'
       - task: Files-Validator@1
         displayName: 'Validating JSON'
         inputs:
           rootDir: '$(Pipeline.Workspace)/s/Onboard'
           validateXML: false
           validateJSON: true
           validateYAML: false
           validatePS: false
       - task: DeleteFiles@1
         displayName: 'Remove unneeded files'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
       - script: |
          git config --global user.email "marcackermann860@gmail.com"
          git config --global user.name "marcackermann86"
          git checkout master
          git add --all
          git commit -m "Moving deployed customers"
          git push origin master
         workingDirectory: '$(Pipeline.Workspace)/s/Onboard/Completed'