trigger:
 paths:
   include:
     - Onboard/*.json

stages:
- stage: build_onboarding_file
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-latest'
      steps:
       - checkout: self
         persistCredentials: true
         fetchDepth: 0
       - task: CopyFiles@2
         displayName: 'Copy new customer onboarding json'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          TargetFolder: '$(Pipeline.Workspace)/s/Onboard/Completed'
       - task: Files-Validator@1
         inputs:
           rootDir: '$(Pipeline.Workspace)/*.json'
           validateXML: false
           validateJSON: true
           validateYAML: false
           validatePS: false
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: OnboardingFile'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          ArtifactName: OnboardingFile
       - script: |
          git config --global user.email "marcackermann860@gmail.com"
          git config --global user.name "marcackermann86"
          git checkout $(env:Build_SourceBranchName)
          git add --all
          git commit -m "Moving deployed customers"
          git push origin $(env:Build_SourceBranchName)
         workingDirectory: '$(Pipeline.Workspace)/s/Onboard/Completed'