name: Build and deploy Sentinel for new customers
resources:
 pipelines:
   - pipeline: Scripts
     source: 'scriptsCI'
trigger:
 paths:
   include:
     - Onboard/*.json
stages:
- stage: get_new_onboarding_file
  displayName: 'Getting new customer onboarding file'
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
  jobs:
    - job:
      steps:
       - task: CopyFiles@2
         displayName: 'Copy new customer onboarding json'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          TargetFolder: '$(Pipeline.Workspace)/s/Deploy'
       - task: Files-Validator@1
         displayName: 'Validating JSON'
         inputs:
          rootDir: '$(Pipeline.Workspace)/s/Deploy/*.json'
          validateXML: false
          validateJSON: true
          validateYAML: false
          validatePS: false
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: OnboardingFile'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)'
          Contents: '*.json'
          ArtifactName: OnboardingFile
- stage: customer_deployment
  displayName: 'Deploying to Customer environment'
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
  jobs:
    - job:
      steps:
        - download: current
          artifact: OnboardingFile
          patterns: '*.json'
        - template: ../Pipelines/OnboardCustomer.yml
          parameters:
            OnboardingFile: 'onboarding.json'
- stage: cleanup_onboarding_file
  displayName: 'Clean up onboarding files'
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
  jobs:
    - job: Cleanup
      steps:
       - checkout: self
         persistCredentials: true
         fetchDepth: 0
       - task: CopyFiles@2
         displayName: 'Copy new customer onboarding json to completed'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
          TargetFolder: '$(Pipeline.Workspace)/s/Onboard/Completed'
       - task: Files-Validator@1
         displayName: 'Validating JSON'
         inputs:
           rootDir: '$(Pipeline.Workspace)/s/Onboard'
           validateXML: false
           validateJSON: true
           validateYAML: false
           validatePS: false
       - task: DeleteFiles@1
         displayName: 'Remove unneeded files'
         inputs:
          SourceFolder: '$(Pipeline.Workspace)/s/Onboard'
          Contents: '*.json'
       - script: |
          git config --global user.email "marcackermann860@gmail.com"
          git config --global user.name "marcackermann86"
          git checkout master
          git add --all
          git commit -m "Moving deployed customers"
          git push origin master
         workingDirectory: '$(Pipeline.Workspace)/s/Onboard/Completed'