# This is the Template that is used from the Main pipeline
# This template contains all the required steps
parameters:
  - name: OnboardingFile
    displayName: Enter the onboarding JSON for the new customer
    type: string

jobs:
  - deployment: 'New_Customer_Sentinel'
    displayName: 'Deploy Sentinel Solution'
    pool:
      name: Azure Pipelines
      vmImage: 'windows-latest'
    #environment: ${{ parameters.CustomerName }}
    strategy:
      runOnce:
        preDeploy:
          steps:
            - checkout: self
            - task: PowerShell@2
              displayName: 'Prepare powershell environemnt'
              inputs:
                targetType: 'Inline'
                script: |
                  Install-Module AzSentinelTools -Scope CurrentUser -AllowClobber -Force
                  Import-Module AzSentinelTools
                pwsh: true
            - task: AzurePowerShell@4
              displayName: 'Deploy resource group for Sentinel workspace'
              inputs:
                azureSubscription: ${{ parameters.ServiceConnectionName }}
                ScriptPath: '$(Pipeline.Workspace)/s/Scripts/DeployResourceGroup.ps1'
                ScriptArguments: '-Name ${{ parameters.ResourceGroupName }} -Location ${{ parameters.ResourceGroupLocation }} -Tag @{H="${{ parameters.HostingNumber }}"}'
                azurePowerShellVersion: LatestVersion
                pwsh: true
            - task: AzurePowerShell@4
              displayName: 'Deploy log analytics workspace for Sentinel'
              inputs:
                azureSubscription: ${{ parameters.ServiceConnectionName }}
                ScriptPath: '$(Pipeline.Workspace)/s/Scripts/DeployLogAnalyticsWorkspace.ps1'
                ScriptArguments: '-Location ${{ parameters.ResourceGroupLocation }} -Name ${{ parameters.WorkspaceName }} -ResourceGroupName ${{ parameters.ResourceGroupName }} -Tag @{H="${{ parameters.HostingNumber }}"}'
                azurePowerShellVersion: LatestVersion
                pwsh: true
        deploy:
          steps:
            - checkout: self
            - task: PowerShell@2
              displayName: 'Prepare environemnt'
              inputs:
                targetType: 'Inline'
                script: |
                  Install-Module AzSentinelTools -Scope CurrentUser -AllowClobber -Force
                  Import-Module AzSentinelTools
                pwsh: true
                
            - task: AzurePowerShell@4
              displayName: 'Enable and configure Azure Sentinel'
              inputs:
                azureSubscription: ${{ parameters.ServiceConnectionName }}
                ScriptPath: '$(Pipeline.Workspace)/s/Scripts/EnableSentinel.ps1'
                ScriptArguments: '-Name ${{ parameters.WorkspaceName }} -ResourceGroupName ${{ parameters.ResourceGroupName }}'
                azurePowerShellVersion: LatestVersion
                pwsh: true
