# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: build and deploy Sentinel
resources:
 pipelines:
   - pipeline: Scripts
     source: 'scriptsCI'
trigger:
 paths:
   include:
     - Onboarding/*

stages:
- stage: build_onboarding_file
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-latest'
      steps:
       - task: CopyFiles@2
         displayName: 'Copy Onboarding'
         inputs:
          SourceFolder: Onboard
          TargetFolder: '$(Pipeline.Workspace)'
       - task: Files-Validator@1
         inputs:
           rootDir: '$(Pipeline.Workspace)/*.json'
           validateXML: false
           validateJSON: true
           validateYAML: false
           validatePS: false
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: OnboardingFile'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)'
          ArtifactName: OnboardingFile

- stage: deploy_resource_group
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-latest'
      steps:
      - download: current
        artifact: OnboardingFile
      - download: Scripts
        patterns: '*.ps1'
      - task: AzurePowerShell@4
        displayName: 'Deploy Resource Group'
        inputs:
         azureSubscription: 'ARM Sub 1'
         ScriptPath: '$(Pipeline.Workspace)/s/Scripts/DeployResourceGroup.ps1'
         ScriptArguments: '-OnboardingFile onboarding.json'
         azurePowerShellVersion: LatestVersion
         pwsh: true

- stage: deploy_log_analytics_workspace
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-latest'
      steps:
      - download: current
        artifact: OnboardingFile
      - download: Scripts
        patterns: '*.ps1'
      - task: AzurePowerShell@4
        displayName: 'Deploy Log Analytics Workspace'
        inputs:
         azureSubscription: 'ARM Sub 1'
         ScriptPath: '$(Pipeline.Workspace)/s/Scripts/DeployLogAnalyticsWorkspace.ps1'
         ScriptArguments: '-OnboardingFile onboarding.json'
         azurePowerShellVersion: LatestVersion
         pwsh: true

- stage: install_sentinel
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-latest'
      steps:
      - download: current
        artifact: OnboardingFile
      - download: Scripts
        patterns: '*.ps1'
      - task: AzurePowerShell@4
        displayName: 'Install Sentinel'
        inputs:
         azureSubscription: 'ARM Sub 1'
         ScriptPath: '$(Pipeline.Workspace)/s/Scripts/InstallSentinel.ps1'
         ScriptArguments: '-OnboardingFile onboarding.json'
         azurePowerShellVersion: LatestVersion
         pwsh: true
